{% set name = "fakemap" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fakemap-{{ version }}.tar.gz
  sha256: 17816b68b93d6b8dc188bda3b69c21acfa8272af260f4bf00e114bc782e64e97

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - folium
    - ipyleaflet
    - geopandas
    - httpx

test:
  imports:
    - fakemap
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MattAGUT/fakemap
  summary: Python Boilerplate contains all the boilerplate you need to create a Python package.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MattAGUT
